openapi: 3.0.4
info:
  title: Domain Availability
  description: >-
    Domain Availability Checker is a simple tool for checking the availability
    of a domain. It returns if the domain is available or not.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/domainavailability:
    get:
      summary: Check Domain Availability
      description: Check if a domain is available
      operationId: domainavailability
      parameters:
        - name: domain
          in: query
          schema:
            type: string
          required: true
          description: The domain to check if it is available
          example: myspace.com
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  domain: myspace.com
                  available: false
                  owner:
                    registrar: GoDaddy.com, LLC
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
