name: apiverve_domainavailability
description: Domain Availability Checker is a simple tool for checking the availability of a domain. It returns if the domain is available or not.
version: 1.1.14
homepage: https://domainavailability.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/domainavailability-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
